package com.brilliance.webservicefortest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-12-18T16:53:30.472+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "CxfWebServiceImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/brilliance/CXFService?wsdl",
                  targetNamespace = "http://webserviceFortest.brilliance.com/") 
public class CxfWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webserviceFortest.brilliance.com/", "CxfWebServiceImplService");
    public final static QName CxfWebServiceImplPort = new QName("http://webserviceFortest.brilliance.com/", "CxfWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/brilliance/CXFService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/brilliance/CXFService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    

    /**
     *
     * @return
     *     returns CxfWebServiceImpl
     */
    @WebEndpoint(name = "CxfWebServiceImplPort")
    public CxfWebServiceImpl getCxfWebServiceImplPort() {
        return super.getPort(CxfWebServiceImplPort, CxfWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfWebServiceImpl
     */
    @WebEndpoint(name = "CxfWebServiceImplPort")
    public CxfWebServiceImpl getCxfWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CxfWebServiceImplPort, CxfWebServiceImpl.class, features);
    }

}
