package com.brilliance.webservicefortest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-12-18T16:57:07.044+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://webserviceFortest.brilliance.com/", name = "WebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAge", targetNamespace = "http://webserviceFortest.brilliance.com/", className = "com.brilliance.webservicefortest.GetAge")
    @WebMethod
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://webserviceFortest.brilliance.com/", className = "com.brilliance.webservicefortest.GetAgeResponse")
    public int getAge(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWelcome", targetNamespace = "http://webserviceFortest.brilliance.com/", className = "com.brilliance.webservicefortest.GetWelcome")
    @WebMethod
    @ResponseWrapper(localName = "getWelcomeResponse", targetNamespace = "http://webserviceFortest.brilliance.com/", className = "com.brilliance.webservicefortest.GetWelcomeResponse")
    public java.lang.String getWelcome(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
